apiVersion: v1
kind: Service
metadata:
  name: healthcare-gradio-service
spec:
  type: LoadBalancer
  selector:
    app: healthcare-gradio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860